on:
  push:
    branches: main
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and publish

jobs:
  imagename:
    runs-on: ubuntu-latest
    outputs:
      lowercase: ${{ steps.lowercase.outputs.test }}
    steps:
      - id: lowercase
        run: echo "::set-output name=test::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
  job2:
    runs-on: ubuntu-latest
    #container: ghcr.io/${{needs.imagename.outputs.lowercase}}:main
    needs: imagename
    steps:
      - run: echo ${{needs.imagename.outputs.lowercase}}
